services:
  - type: web
    name: pharmacy-workflow-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd fastapi && uvicorn myapi:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
